{% set name = "furo" %}
{% set version = "2024.1.29" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/furo-{{ version }}.tar.gz
  sha256: 4d6b2fe3f10a6e36eb9cc24c1e7beb38d7a23fc7b3c382867503b7fcac8a1e02
  patches:
    - 0001-set-node-version-to-18.15.0.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  script_env:
    - STB_USE_SYSTEM_NODE=1

requirements:
  host:
    - flit-core >=2,<4
    - pip
    - python >=3.7
    - sphinx-theme-builder
    - nodeenv
    - nodejs ==18.15.0
  run:
    - beautifulsoup4
    - pygments >=2.7
    - python >=3.7
    - sphinx >=6.0,<8.0
    - sphinx-basic-ng


test:
  imports:
    # This is a dirty hack because sphinx.application
    # isn't available with a simple `import sphinx`
    - sphinx.application
    - furo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pradyunsg/furo
  summary: A clean customisable Sphinx documentation theme.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asmeurer
    - gforsyth
